[tool.portray.mkdocs.theme]
favicon = "https://aws-ia.github.io/assets/img/logonav.png"
logo = "https://raw.githubusercontent.com/aws-quickstart/taskcat/master/assets/docs/images/logo.png"
name = "material"
palette = {primary = "deep orange", accent = "orange"}


[[tool.portray.mkdocs.nav]]
 Home = "README.md"

[[tool.portray.mkdocs.nav]]
aws-ia = "https://aws-ia.github.io/?target=_blank" 

[[tool.portray.mkdocs.nav]]
Schema = "docs/schema/taskcat_schema.md"

[[tool.portray.mkdocs.nav]]
API = "docs/apidocs/taskcat/index.html"

[tool.portray]
modules = [
'taskcat',
 'taskcat._cfn',
 'taskcat._cli_modules',
 'taskcat.testing',
 'taskcat_plugin_testhook',
 'taskcat/_amiupdater.py',
'taskcat/_cli_core.py',
'taskcat/_client_factory.py',
'taskcat/_common_utils.py',
'taskcat/_config.py',
'taskcat/_dataclasses.py',
'taskcat/_legacy_config.py',
'taskcat/_logger.py',
'taskcat/_name_generator.py',
'taskcat/_project_generator.py',
'taskcat/_s3_stage.py',
'taskcat/_s3_sync.py',
'taskcat/_template_params.py',
'taskcat/_tui.py'
]
