[tool.portray.mkdocs.theme]
favicon = "https://aws-ia.github.io/assets/img/aws-ia-taskcat.png"
logo = "https://aws-ia.github.io/assets/img/logonav.png"
name = "material"
palette = {primary = "black", accent = "orange"}

[tool.portray.mkdocs]
extra_css = ['docs/custom.css']

[[tool.portray.mkdocs.nav]]
 Home = "README.md"

[[tool.portray.mkdocs.nav]]
Schema = "docs/schema/taskcat_schema.md"


